### ISSUE TITLE
Nearby Recycling Centers - Sorted List

### ISSUE THREAD

**Issue by Djadih** [mpontikes/Our-Green-Routine#25]
Sorts list of nearby recycling centers, displays only the nearest 5.

**Comment by ElginAllen** [comment]
The earth911 API request displays nearest 100. Currently, we need to implement the materials database so that we can search for locations based on location AND material-to-recycle.

**Comment by ElginAllen** [comment]
The API data is parsed. All we need to do to close this issue is display the nearby locations on the mapView and .setText of the location fields.
