### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by mpontikes** [mpontikes/Our-Green-Routine#7]
- Description of the site, its purpose, its intended users
- Group name
- Group members
- For each member: name, photo, bio, major, responsibilities, number of commits, number of issues, number of unit tests
- Stats: total number of commits, total number of unit tests, total number of issues
- Data: links to the data sources, description of how each was scraped
- Tools: tools used, describe their use
- Link to the GitHub repo

**Comment by ElginAllen** [comment]
working on this. got scrolling working

**Comment by ElginAllen** [comment]
finished this except for stats. michael is the pro and is currently a pro working on it

**Comment by mpontikes** [comment]
its done
