### ISSUE TITLE
A Written Report

### ISSUE THREAD

**Issue by mpontikes** [mpontikes/Our-Green-Routine#8]
Your report must include:
- Github repo link, Team information (full name, email, github username), Team Canvas Color/Bird and Project Name
- Project lead for this phase
- Website URL if you are doing a web application
- Description of tasks completed for this phase, and the screens, features and functionality produced in this phase - this will hopefully match the phase I deliverables from your proposal. Be specific. 
- Design: Describe the design of your application. Use UML diagrams. 
- Requirements: User stories for this phase. Refine your use case diagrams.
- Tools, software, frameworks: what did you use in this phase?
- Testing: Describe the testing you've completed for your application

**Comment by Djadih** [comment]
finito
